### PR TITLE
[WIP] Mac & Linux support

### LINKED ISSUE #32: CoreCLR / unix port
Can we make it work on CoreCLR / unix?

### PR DESCRIPTION
**Pull request by cspotcode**
This is not ready to merge yet, but I've started working on Mac and Linux support.  It will fix #32 when it's finished.

Unfortunately it looks like ServiceModel does not work on .net core, so I had to reimplement RPC via named pipes.  This turned into a much bigger project than I was expecting, but hopefully the resulting code is not too complicated.

# service.psm1

This file implements the JSON RPC protocol.

## ServiceHost

Server instance of the `Service`.  Creates a named pipe server, listens for connections, and proxies requests to the `Service` via method calls, sending return values back over the named pipe.

## ServiceProxy

Client instance of the `Service`.  Connects to ServiceHost via named pipe.  Loosely implements the IService interface.

# named-pipe-ipc.cs:

## IpcServer

This is an IPC server that uses named pipes to solicit requests from clients and return responses.  The request and response are both a single line of UTF8-encoded input, so it can't contain \r or \n.  It passes each request string to a delegate which is expected to return a response string.  It waits for connections in a dedicated thread.

## IpcClient

This is an IPC client that connects to an IpcServer via named pipes.  It implements a `request()` method which sends a request string to the IpcServer and returns the response string.

## MessagePipe

Implements a shared API for both client and server to send and receive UTF8-encoded single-line messages.  The named pipe server or client is created and then passed to MessagePipe.

## PowerShellInvoker

Invokes delegates in a PowerShell runspace and returns their return value or throws their thrown exception.  If a Delegate is created from a PowerShell ScriptBlock, it *must* run in a PowerShell runspace, which means we can't merely `Invoke` it from C#.  This class handles all those messy details.

### CODE REVIEW

**Comment by cspotcode** [comment]
Good idea, I added a basic Travis configuration.

I'm very new to C# and PowerShell's concurrency behavior, so I made a few mistakes in the code.  I didn't know about PowerShell/PowerShell#3651 which says that class methods refuse to run concurrently in other runspaces.  This means that the concurrent call to ServiceHost.callServiceMethod is hanging.  (https://github.com/cspotcode/ZLocation/blob/966d6fe4e07d6bb73836378966e86433bf990a10/ZLocation/service.psm1#L15)  I think I can fix it by creating the ServiceHost in a background runspace.

If you have any suggestions or criticisms, I'll be grateful to hear them.  I'm still learning a lot.  Otherwise I'll finish fixing the bugs in the next few days and send you a message when it's functional.

**Comment by vors** [comment]
This is quite a big change, I would not be able to look at it immediately. 
I will try my best to do the review by the end of this week. 

I'm very excited that you started to tackle that. 👍

**Comment by vors** [comment]
I tried it locally, just got the

```
WARNING: ZLocation Pipe become broken :( ZLocation is now self-disabled. 
```

Does it work in any form for you?
I'm testing it on macOS.

The runspace-bound methods was a change that perhaps should have more thoughts. Both bound and unbound instances have they problems, that probably more obvious for unbound instances. Perhaps we will revisit it at some point.

**Comment by cspotcode** [comment]
I don't believe the code in the PR is working.  I did manage to fix it on
my laptop, but before pushing the fixes I ran into unrelated laptop
problems.  I should have my laptop fixed and be able to push the fixed code
in 2 days.  Sorry for the inconvenience.

I've learned more about runspaces and threads in the past few days.  I
created the ServiceHost instance in a dedicated background runspace, which
fixed the hanging calls to ServiceHost.callServiceMethod.  I also
discovered that the return value of `Service.Get` --
`Enumerable<KeyValuePair<string, double>>` -- was not serializing as I
expected, so I added a manual conversion.

I think I should also simplify the code.  I was initially trying to make
each component generic and reusable, but it's probably better to keep
things simple.  I'll do that when my laptop is fixed.

Thanks for your time!

On Jun 15, 2017 00:32, "Sergei Vorobev" <notifications@github.com> wrote:

I tried it locally, just got the

WARNING: ZLocation Pipe become broken :( ZLocation is now self-disabled.

Does it work in any form for you?
I'm testing it on macOS.

The runspace-bound methods was a change that perhaps should have more
thoughts. Both bound and unbound instances have they problems, that
probably more obvious for unbound instances. Perhaps we will revisit it at
some point.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/vors/ZLocation/pull/33#issuecomment-308625880>, or mute
the thread

**Comment by vors** [comment]
Maybe http pipe would be a good way https://github.com/powershell/polaris

**Comment by vors** [comment]
@cspotcode Any updates here?

**Comment by cspotcode** [comment]
No, I haven't had a chance to touch this in a while.  But I think we should
implement this LiteDB solution someone else proposed.  All this IPC stuff
is way too complicated.  I was wrestling with it for a while, and even
though I got it working, there's too much code.

**Comment by cspotcode** [comment]
Closing in favor of #46, which is much simpler.

**Pull request closed without merging**
