### PR TITLE
Spelling fixes, Aliased Tab Completion, Rank Aging, and Jumps to Current Directories and Full Paths

### PR DESCRIPTION
**Pull request by Devagamster**
Finally figured out how to use GitHub and got them checked in.

### CODE REVIEW

**Comment by Devagamster** [comment]
I understand that this is a big set of changes. As a recap:

- Fixed Spelling Errors in Comments
- Made it so that any alias for Set-ZLocation works with the tab completion
- Added directories found in the current directory to the match hash after it is returned from the server with a weight of 9000 so that z can be used to navigate locally with the fuzzy text search
- Added ageing to the data such that once the total sum of all of the weights hits 9000 every weight is multiplied by 0.99. If any weights after that are below 1 they are then removed from the server. This is the same algorithm found in z.sh.
- Since weights can be removed if you are at 9000 frequently, I made it so that the increment is 1.1 so that any directory is not removed from the store immediately but has to be decremented 10 times first.

Let me know if you want any of these features removed or changed. Very cool project and with these changes I think it is even more stable and fast than Jump-Location! Let me know if you need anything else done on it :)

**Comment by vors** [comment]
Thanks! Great suggestions, I would love to work with you to incorporate them.
Currently we have a mix of: 
- simple format / spelling changes
- bugfixes
- behaviour changes

It would be really helpful to separate them: things like spelling can be quickly reviewed and merged. Bugfixes requires test coverage and reading more code. Behavior changes requires discussion, before making any call.

Since most of your changes are formatting / spelling and their significantly increase the size, it's harder to review all of them together.

Can we do the following:
1) create a separate pull request for format / spelling changes
2) create a separate pull request to fix #16 
3) Open an issue to discuss behavior changes aligned with `z.sh`

About the last one: `z.sh` algorithm is based on time spent in directory and all heuristics like `* 0.99` are works fine with this approach. `ZLocation` uses simpler weight function: number of commands run from the directory, suggested by @leeholmes . I tried both approaches and found that number of runs works just fine. Meanwhile, number of spent time has one huge down-side: it's sensitive to locking the machine for a day in some unusual directory, which bumps the weight for it and messes all your future experience. 

For that matter  heuristics from `z.sh` still may apply, but they should be considered thoughtfully.

**Comment by Devagamster** [comment]
Good plan. I will attempt to separate out into multiple pull requests. I am relatively new to Github, so I was struggling to figure out how to do that. Do I create a different fork for each one? Not sure...

**Comment by Devagamster** [comment]
I also wanted to ask how you develop your scripts? I see weird psd1 and psm1 extensions which I am not familiar with, and I found it difficult to debug the C# code. That said, I'm not used to writing bigger powershell scripts than just a few lines or creating powershell modules, so it could just be I'm just inexperienced :P

**Comment by vors** [comment]
I wrote a [GettingStartedWithGitHub](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md) for our work project. It may be a good starting point to answer some of your questions. Almost all information is applicable to any github repository.

psd1 — module manifest file (contains some meta-info like version, description, etc)
psm1 — PowerShell module file (think about 'ps1 vs psm1' like 'exe vs dll')

I didn't debug cs code, code is quite simple. Didn't have problems with it so far.
CS code exists only because I cannot create a WCF entities directly from PowerShell (which I hope would be possible in the next version of PS).

I use SublimeText with [PowerShell plugin](https://github.com/SublimeText/PowerShell) for development and PowerShell_ISE interchangeable.

**Comment by Devagamster** [comment]
That should help a lot! Thanks. Ill get working on it shortly.

Sent from Windows Mail

**Comment by vors** [comment]
@Devagamster any updates? Let me know if I can help you with git / github or anything else.

**Comment by Devagamster** [comment]
Sorry for being gone for a bit. I just started a new internship for the summer, so I was distracted. I think I should be able to help in the evenings however and get working on separating the concerns of this pull request more effectively. I think I will make one pull request with the spelling changes and white space fixes, and one which does the alias fix.

After I do that I think we should look into getting a plugin system working. Like I said on a different thread, I don't really know what that would look like in PowerShell (my background is c#) but I would definitely be interested in helping in any way I can.

**Comment by Devagamster** [comment]
Here is the spelling changes commit. I delete the other changes and will re add them after this request is merged.

**Comment by Devagamster** [comment]
I should say if this request is merged ;)

**Comment by vors** [comment]
Thank you for a prompt actions! Unfortunately, I cannot merge it as is, again. You changes contains two parts:

- Spelling fixes, that I would like to merge.
- Formatting changes, that I don't see the reason to merge.

For example, you removed

```
#
#
#
```

in one place. I had it there intentionally to separate two sections.

Changing blank line style (trimming ending spaces, etc) doesn't provide enough value to justify potential merge conflicts for other people, caused by them. At least, this is not the good start for contributions. Here is an excellent article about contribution practices, that explains my point: http://tirania.org/blog/archive/2010/Dec-31.html

I suggest use more granular commits, in our case it can be two commits (one for spelling, one for formatting). This way, you would be able to simply revert one of them and update PR. Commits are cheap, please use them. :)

**Comment by Devagamster** [comment]
I apologize for my naive pull request. I'm fairly new to this and a lot of the corrections were automatic in my mind with regards to formatting. I will try again when I get the chance.

**Comment by vors** [comment]
Don't worry, it's wonderful that you are willing to contribute.

**Comment by vors** [comment]
@Devagamster closing this PR, because it was suppressed by #31

**Pull request closed without merging**
