### PR TITLE
Improve install/removal of modified prompt function

### LINKED ISSUE #59: Register-PromptHook breaks posh-git prompt
The [posh-git ](https://github.com/dahlbyk/posh-git) module injects its own prompt function that provides various features including a Git status display in the prompt.  As soon as you `Import-Module ZLocation`, it breaks the posh-git prompt function i.e. the prompt degenerates to `PS>`:

image

The reason it breaks is that the `Register-PromptHook` function doesn't just append `Update-ZLocation $pwd` to the front of the prompt function.  It creates a new scriptblock in the scope of the ZLocation module. 

https://github.com/vors/ZLocation/blob/2ccc541f87d98c7cfa72cee6fd423c8a195f7aac/ZLocation/ZLocation.psm1#L45-L59

This breaks posh-git because it created its prompt scriptblock within the posh-git module e.g.:

```
C:\Users\Keith
09-11 20:05:57 3> (Get-Command Prompt).Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Expand-GitCommand, Form...


C:\Users\Keith
09-11 20:06:00 4> ipmo ZLocation
PS>(Get-Command Prompt).Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        __DynamicModule_3cd9b6f8-0961-47...
```
The results in errors that prevent the posh-git prompt function, recreated in a new scriptblock, from being able to access private, module-scoped functions:
```
PS>$error
The term 'EscapeAnsiString' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
EscapeAnsiString : The term 'EscapeAnsiString' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:102 char:37
+         $global:PoshGitLastPrompt = EscapeAnsiString $prompt
+                                     ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (EscapeAnsiString:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
One possible workaround it to special case `posh-git`.  Yeah I don't think it is a great solution but it does work.  :-)  This is done by a simple check for a posh-git defined prompt function in the `Register-PromptHook` function and then injecting a scriptblock that invokes `Update-ZLocation $pwd`:
```
function Register-PromptHook
{
    param()

    # If posh-git is supplying the prompt function, inject update command via the posh-git VcsPromptStatuses hook
    $prompt = Get-Command prompt -CommandType Function -ErrorAction SilentlyContinue
    if ($prompt -and $prompt.module -and $prompt.module.name -eq 'posh-git') {
        $global:VcsPromptStatuses += { [void](Update-ZLocation $pwd) }
        return
    }
…
```
I'm definitely open to other ideas that are more widely applicable.  Ideally the PowerShell engine would expose an event that fires whenever the FileSystem provider changes location.

BTW the above solution is dependent on module import order.  It will work if ZLocation is imported **after** posh-git.  If ZLocation is imported before posh-git, then posh-git punt on modifying the prompt function because it "appears" the user has their own customized prompt.  

cc @dahlbyk

### PR DESCRIPTION
**Pull request by rkeithhill**
On PowerShell Core >= 6.1, use new LoccationChangedAction event handler.

Fix #59

### CODE REVIEW

**Comment by vors** [comment]
I just realized that `LocationChangedAction` and `prompt` are called in very different circumstances. Currently the algorithm adds `1.0` to the weight of the directory **when we run any command** in the directory. That's quite different.

**Comment by rkeithhill** [comment]
You mean that within the pompt function, we should only call Update-Location if the dir has changed?  If so, that should be easy to fix.

**Comment by vors** [comment]
Let me lay out an example:

I'm going to directory `~/foo` and run there 3 commands

```
PS /Users/vors> cd ./foo/
PS /Users/vors/foo> ls 
PS /Users/vors/foo> pwd

Path
----
/Users/vors/foo


PS /Users/vors/foo> ls
PS /Users/vors/foo> 
```

In the `prompt`, the weight of `/Users/vors/foo` bumped +3.
In the `LoccationChangedAction`, the weight of `/Users/vors/foo` was not even bumped once. Maybe you can make it to bump it once on the original change of the directory (not how it works according to my testsing) but that doesn't change the situation that location change is not the right hook: something like command execution would be the right hook (aka prompt).

**Comment by rkeithhill** [comment]
OK, I'll rip out the hook for `LocationChangedAction` and make it always use the "modified" prompt hook.

**Comment by rkeithhill** [comment]
The PR feedback has been addressed.  I removed the use of the `LocationChangedAction`.

**Comment by vors** [comment]
Sounds good, thank you!

**Pull request merged**
